- Makefile
- README.md
- evaluation/feature_test.go
- evaluation/reflection_test.go
- go.sum
- types/bool.go
* Added default target 'all'.    Just running ```make``` should be enough to build, check and test the code
* Use ```go env``` to determine the correct place to install binaries
* Updated the version of the linter being used
* introduced gofmt, gosec and golint checks.  These are run automatically as part of all
*  Added goreport card to README.md
Additional changes to the code are a result of running gofmt.
> (MAINT) This updates some targets in the makefile to building and check the code

- cache/cache.go
- cache/lru.go
- cache/persist.go
- client/client.go
- client/config.go
- client/options.go
- dto/target_builder.go
- evaluation/feature.go
- evaluation/feature_test.go
- evaluation/target.go
- evaluation/target_test.go
- go.mod
- rest/adapter.go
- storage/file.go
- storage/storage.go
- stream/sse.go
Why In the go.mod the module was defined as being .v0.  It is not
neccessary to version the default (v0) version of a module.  It is implictlity a v0.
The format was also wrong as it should be a /vX as opposed to .vX.
How Remove the .v0 from the go.mod file and updated all deps.
> (MAINT) This removes the unnecessary v0 module declaration

- client/client.go
- client/client_test.go
- client/config.go
- client/helpers_test.go
- client/options.go
- evaluation/feature.go
- go.mod
- go.sum
If a flag has pre-requisistes then they should be evaluated before returning the
flag.  If a pre-req is not met, then we return the offVariation for the flag.
In order to make this more testable, the persistence store can be disabled, and the http client used in API requests can be overwritten.
> (FFM-725) Implement Pre-Req Evaluation

- client/client.go
- evaluation/feature.go
- evaluation/feature_test.go
What:
This change returns a variation struct rather than just the value
from an evaluation call.
Why:
In some circumstances we need both the value of the variation and its identifier.
By returning the variation the caller gets all this information.
The Client API remains unchanged, where BoolVariation will simply return a bool.
> (FFM-767) Return variation rather than value

- evaluation/feature.go
- evaluation/target.go
- evaluation/target_test.go
What: Adding check to ensure we only use operator if it is non-nul.
Why: Its possible for a clause to have a nil operator, but the only valid
scenario for this, is if it is a segmentMatch operation.  We need protective code
to ensure we don't accidently call a nil operator.
> (MAINT) If an operator is nil, it can cause a panic

- evaluation/feature.go
- evaluation/segment.go
- evaluation/segment_test.go
- evaluation/target.go
- log/log.go
- rest/adapter.go
What:
* change logic so the include/exclude rules use target identifier rather name to be consistent
with how the rules are stored.
* Make exclude list take precedence over include list and rules.
* Process segment rules as OR rather than AND.
Why:
When creating segment include/exclude lists the server only stores target identifiers not
names, so this logic needed to be updated so the lists were correctly evaluated.
The exclude list was being evaluated last, which meant we could not include all users via
a rule, but exclude one via a list.  This is consistent with how the Java SDK behaves.
Segment rules should be OR'd, but they were being treated like flag clauses and were being
AND'd which meant conflicting rules would prevent targets from correctly being included.
> [FFM-1219]: Fix how segment rules are processed

- evaluation/feature.go
- evaluation/feature_test.go
What:
Append segments from the target segment variation map, to the list of segments
that should be loaded by a feature config.
Why:
There are two ways to add a segment to a flag.
1) From segments added through flag rules
2) From segments in the variation target map.
The first use-case worked, because we parse the rules and create a list of segments to load
from the cache, prior to evaluating rules.
The second use-case did not work, as we didn't append segments from the variation target map
in the list.
> [FFM-1251]: Rules for flags added directly to segment not working

- evaluation/target.go
- evaluation/target_test.go
*what*
When you add a 'target group match' rule to a flag the attribute field is empty. So we would show an invalid type error. this change simply ignores empty attributes. 
*Why*
Otherwise we would display a warning log each time that the type is invalid, despite the fact that it is ok.
> (FFM-1290) Ignored empty evaliation attibute

- evaluation/target.go
- types/bool.go
- types/bool_test.go
- types/int.go
- types/int_test.go
- types/number.go
- types/number_test.go
- types/slice.go
- types/slice_test.go
- types/string.go
- types/value.go
This change fixes the bool, int and number comparisons.  It replaces
a cast with the appropriate function from the strconv package.
The slice type is implemented with support for in, contains and equals
operators.
Customers can store target attributes as strings, float64, bool and slices.
When creating a rule the value is always a slice of strings.
The code was trying to cast a string to a int, float etc which does not work.
This caused rules evaluations to fail.
Added unit tests to verify the type operators now work as expected.
> [FFM-1452]: Fix bool, int and number comparisons + implement slices

- Makefile
- storage/file.go
Added a check that the file is not nil before calling close
This was identified by gosec as an unsafe call to Close()
> (maint) Fix gosec issues

- analyticsservice/analytics.go
- client/client.go
**Changes**
Currently when enableStore is set to false we still start the persistCron job that saves to the store every minute. I've changed it to skip starting this cron when this flag is false.
Also made some small logging changes
> (FFM-1855) Don't start persistCron when enableStore false

- analyticsservice/analytics.go
**What**
Lower metrics log level to debug
**Why**
We have a lot of valuable logs at info level e.g. SSE event coming in, updates on polling progress which I'd like to see but I don't want my logs cluttered by these two metric logs printing every minute.
This is especially a problem where we can have 10 sdk's running in parallel and would like the logs to be silent unless theres an error or an event happens
> (FFM-1815) Lower metrics log level

- client/client.go
- go.mod
- stream/sse.go
**What**
For our SDK's the desired functionality if we lose connection is to poll the data directly to collect any updates we missed then re-establish the stream. There were bugs in this area that this pr addresses. 
**Fixes**
1. When running the reconnect poll via the `retrieve` function it included logic only required on startup i.e. pushing a value to the `c.initialized` channel - this meant when called later nobody was listening on the channel and the thread would hang forever. 
2. We didn't check that the data poll succeeded before trying to restart the stream
3. We didn't run the `onDisconnect` logic if the stream failed to start up - only if it disconnected, this meant if this path was hit the stream wouldn't start but `c.streamConnected` would still be set to true preventing any …
> (FFM-1857) Streaming reconnect

- logger/zap.go
- Adds a new constructor to give the ability to create a ZapLogger from
an existing SugaredLogger
- Adds a getter to return the underlying SugaredLogger that the
ZapLogger uses
We need these changes as a part of this work https://github.com/harness/ff-proxy/pull/32
> Logger updates

- Makefile
- go.mod
OAPI codegen Installation contains 2 steps:
- install runtime lib
- install oapi codegen
if oapi codegen is newer then runtime lib, then services.go will raise errors in code.
> [FFM-1719] makefile modified for oapi install

- client/client.go
**Issue**
We had a 1 minute wait in the streamErr function - this could cause some unexpected behaviour when clashing with the poll interval timer e.g. 
Minute 1: Poll interval runs -> fails to setup stream -> kicks off streamErr func
Minute 2: Poll interval runs -> sets up stream correctly -> streamErr wait finishes which resets streamConnected bool to false
Minute 3: Poll interval runs -> sets up a second stream because it thinks streamConnected is false
The bigger underlying issue I see here is that we rely on getting and setting booleans to represent if a stream is connected or not rather than having an actual stream object that we can check for health and guarantee there will only be the one in the system. This would require a larger refactor though so this should mitigate the bug …
> (MAINT) Remove 1 minute timer on disconnect

- client/client.go
**What**
Add a way for consumers to check if the stream is connected
**Why**
We'd like to consume this in the ff-proxy for the healthcheck endpoint
> (FFM-1842) Add IsStreamConnected func

- client/client.go
- client/config.go
- client/options.go
- stream/sse.go
- stream/stream.go
**What**
- Creates an Interface that clients can implement in order or receive the SSE Events that the SDK gets from Feature Flags
- Adds an option func so clients can pass their own EventStreamListener in, default behaviour is to not have one. 
**Why**
In order to implement streaming in the Proxy we need to be able to get the SSE events after the SDK has updated the cache. This change only forwards the Event to the EventListener after the cache has been updated.
**Testing**
Did the following locally
- Created a basic EventListener in the Proxy and passed it in to the embedded SDK using `WithEventStreamListener`. 
- Changed the Proxy stream handler to just return the Grip Control headers for pushpin
- Ran the Proxy and pointed and SDK at it that was running in streaming mode
- Toggled …
> FFM-2096 Add Interface for hooking into SSE Events

- evaluation/feature.go
- evaluation/feature_test.go
- evaluation/segment.go
- evaluation/segment_test.go
Segments evaluation had two problems:
1) It returned false if any segment evaluate returned false (even if segment was not part of the clause)
2) It evaluated the target in segmentMatch clause against all segments, where it should only evaluate against
the segments defined by the clause.
Evaluation Percentage Rollout was also distributing values incorrectly when there were more than
two variations.
Updated unit tests to ensure segment Evaluation performed as expected
> [FFM-2217]: Evaluation returning wrong result with multiple segments

- client/client.go
**Changes**
Adds the ability to get the connected cluster id
**Why**
The proxy needs to know what cluster we're connected to to forward on some data, we can grab this from the embedded go sdk easily
> (FFM-1750) Get connected cluster

- client/client.go
**Issue**
Metrics weren't working for prod-2 accounts. This is because the clusterIdentifier wasn't being set for metrics requests like it is for client requests (see line 280 - a few lines above my changes in this pr).
**Fix**
Send the cluster identifier 
**Testing**
Tested against prod-1 and prod-2 accounts, working as expected
> (FFM-2513) Add cluster identifier to metrics requests

- evaluation/evaluator.go
- evaluation/util_test.go
It turns out [`attrValue.String()`](https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/reflect/value.go;l=2414) will not return a string value if `attrValue` is an int, boolean or any other non string type. So I've made a change to check the `Kind` of `attrValue` and then do the appropriate conversion for that kind to a string.
> FFM-2934 Bugfix - compare custom attributes based on string values

- client/client.go
- client/client_test.go
**What**
Close wasn't closing streaming connections which meant they would stay open forever. 
**Testing**
Started up the sample sdk locally with it pointing at this version of the SDK and had it stream for a period of time before calling `Close`. Before `Close` was called I could see streamed events in the logs when I toggled a flag on/off and after `Close` was called I was not seeing streamed events in the logs whenever I toggled a flag on/off
The unit test for this is a bit light but I can't see a way to do anything more thorough without extensively refactoring the code in the client. Ideally if we could break the logic in the client out into smaller components we would be able to define some interfaces for the separate bits of logic that the client is doing e.g.
```go
type streamer …
```
> Streaming connections are now closed when you call Close on a client

- analyticsservice/analytics.go
- analyticsservice/analytics_test.go
**What**
Tightens up string conversion around attribute values when we're posting metrics. 
**Why**
Previously if you provided an int value for an attribute then it was being sent to the metrics service as an empty string
**Testing**
Made my golang-server-sample use this branch of the SDK and I could see that integer attributes values were now being received by the metrics service on my local ff-server
> FFM-2514 add function to convert various types to string

- evaluation/target.go
This adds more context to the log message, indicating its occured due to
a target attribute.
We saw vague logs saying "unexpected type: invalid".  It was unclear what the
unexpected type was, or what trigged the messae in the first place.
> [FFM-3261]: Add extra information to the log

- evaluation/feature.go
- evaluation/feature_test.go
There was a bug in the FF-Server where it wasn't evaluating flag values
properly if they had prerequisites. This is becuase the current logic
flow in FeatureConfig.Evaluate doesn't take Prerequisites into account
which meant client SDKs receiving evaluations for flags with
Prerequisites weren't receiving the correct value.
In order to evaluate prerequisites we need the flag we're
evaluating and all of the flags that may be prerequisites of it the only
way I could see to do this was to provide a way to pass in all other
flags. I didn't want to break the existing API for `Evaluate` so added a
new function that could be used for this. 
The way the `Evaluator` handles evaluating prereqs is by looking up the Prerequisite
flags from the cache but we don't have the option to do that from inside …
> FFM-1821 - Prerequisite rules not working on ff-server

- evaluation/feature.go
This change ensures we handle JSON types when evaluating with pre-reqs.
Multivariate flags can contain JSON.  This was missed from the current switch
block.
> [FFM-3441]: Unable to evaluate JSON multivariate

- README.md
- docs/further_reading.md
Some readme updates to follow the standard readme template
> (MAINT) Readme updates

- evaluation/feature.go
- evaluation/feature_test.go
**What**
A bug where MV flags with prerequisite flags are always returning an off state, I also suspect there might have been issues if there are multiple prereq flags set
[FFM-3625](https://harness.atlassian.net/browse/FFM-3625)
**Why**
This was impacting customers using the JS SDK which in turn uses the GO SDK to evaluate flags.
Currently -  the behaviour was comparing the value of a pre requisite flag against the value of a MV flag i.e. true == blue
Now - We check the prerequisites of a flag, and the status of the prereq flag to make sure they match up
**Testing**
Unit tests written for scenarios for single/multiple bools, mv flags with and without targets
Manual testing to ensure the expected behaviour occurred
> FFM-3625 - Flags with pre-reqs always evaluating to off state

- client/client.go
- evaluation/evaluator.go
- evaluation/evaluator_test.go
- logger/nooplogger.go
- tests/evaluator_test.go
**What**
Evaluator logs where not respecting the custom logger
Also changed some info logs to debug to reduce clutter
[FFM-3702](https://harness.atlassian.net/browse/FFM-3702)
**Why**
This is because the custom logger wasn't being passed in, and therefore the default logger was always being used
**Testing**
Manually tested
Unit Tests - because I added this to the evaluator struct, I had to make a nooplogger
> FFM-3702 Adding customer logger for evaluation

- client/client.go
**Issue**
This log printed at info level every time we evaluate a flag so can be very noisy. If we need to debug what was sent to the analytics service we can see it in the detailed analytics service debug logs [here](https://github.com/harness/ff-golang-server-sdk/blob/main/analyticsservice/analytics.go#L148) when it's pushing to ff-server.
**Fix**
Remove the log
> (MAINT) Remove noisy log

- evaluation/evaluator.go
- evaluation/evaluator_test.go
**What**
Change number variation to check for kind 'int' rather than 'number'
[FFM-3974](https://harness.atlassian.net/browse/FFM-3974)
**Why**
Every number variation request has the wrong type because we store them as int's and not numbers in the database
**Testing**
Manually tested
Unit tests changed where appropriate
> Change 'number' to 'int' input on number variations

- evaluation/evaluator.go
- evaluation/evaluator_test.go
- evaluation/feature.go
- evaluation/feature_test.go
- examples/getting_started.go
**What**
Adds a recursive check to check that pre requisite flags with pre requisite flags are honoured
Slight update to example to fulfil docs changes
**Why**
Flags that had nested pre requisites were only being evaluated against the initial pre requisite
**Testing**
Unit Tests
Manual Testing
-- aware that the branching looks out of date, but need to make a tag for 0.0. and for 0.1.
> FFM-4043 - Add checks for nested pre req flags

- .drone.yml
- .github/workflows/ci.yml
- Makefile
- client/client.go
- client/helpers_test.go
- docker/Dockerfile
- go.mod
- pkg/repository/repository.go
- stream/sse.go
- test_wrapper/go.mod
- tests/evaluator_test.go
**What**
1. Update Go to 1.18
2. Change go get to go install for openapi codegen in makefile
3. Allow for custom cache to be honoured when set in client config
4. Add initalLoad flag to prevent outdated check on initial load of flags and segments, because new logic causes a lot of error logging on first load as you are trying to check against something that cannot exist. This is set as true on retrieveFlags, segments, then on event updates set as false. 
5. Update tests so that state is accurately set, was "true"/"false" should be "on"/"off"
6. flagKey and segmentKey is inconsistently set/get across the board
7. Pin Golangci-lint version (issue - https://github.com/golangci/golangci-lint-action/issues/535)
**Why**
Changes are necessary to keep consistency and allow for the proxy/other …
> FFM-4572 - Update Go version, allow custom cache, add initalLoad flag, standardise segment and flags being set

- evaluation/feature.go
- evaluation/feature_test.go
What:
Updates prerequisite checks so that they compare by flag identifier and not value
Updates feature_test.go so that the boolean flag created for a prerequisite test is inline with UI Rules - variation identifiers should be true/false only.
Why:
Was sending back wrong variation when flag identifier and value were not identical for a prerequisite flag
Was sending back wrong variation when prereq bool flag had variation identifiers that weren't true/false
> [FFM-5103] changed prereq matches from value to identifer

- .github/workflows/sonar_analysis.yml
Update the workflow to only run sonarcube on a push to main.
Because this is a public repo, secrets will not be shared from forks, so i we will just scan the main branch.
>  [maint]: Only run the sonarqube scan on push to main

- evaluation/evaluator.go
```
[FFM-5510]: Fixing the condition in evaluator to consider empty slice + Exposing Evaluate function
Small fix to consider empty slice in the condition for clause evaluation
Previously segment.rules would either be nil pointer or pointer to slice with at least one element.
Due to changes made for FFM-4150 we require extra check. 
Locally
```
[FFM-5510]: https://harness.atlassian.net/browse/FFM-5510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-5510]: Fixing the condition in evaluator to consider empty slice + expose Evaluate function

- Makefile
- evaluation/evaluator.go
- tests/evaluator_test.go
Run evaluator tests against the ff-test-grid test-cases
Fix the group rule evaluator which was AND'ing instead of OR'ing the rules
Improve test coverage and fix an evaluator bug
> [FFM-5387]: Fix Golang Group Rule Evaluate and Add Tests

- evaluation/evaluator.go
- evaluation/util.go
- evaluation/util_test.go
**Issue**
Some target segment include rules weren't working for numeric values because when we went to convert these numbers to strings to compare them we always set this value to be an empty string. This meant no targets would be included in the target group correctly. 
**Fix**
Convert all numeric values to strings before the comparison stage
**Testing**
Moved this logic to a new function and added some unit tests, including for the cases that are currently failing
> (FFM-6384) Match target attributes to numbers

- Makefile
- README.md
- examples/code_cleanup/README.md
- examples/code_cleanup/config/rules.toml
- examples/code_cleanup/example.go
**Changes**
Add a flag code cleanup example for the go sdk and some docs on how to run the example. Further docs on how to craft your own custom rules for your own repo will be added to the core https://github.com/harness/flag_cleanup repo shortly.
> (FFM-6794) Add code cleanup example

- client/client.go
- client/config.go
- logger/retryablelogger.go
**Issue**
If you pass in a custom logger using the `harness.WithLogger(myLogger)` builder function there were some places it wasn't being used. 
- Default http client
- Default cache
- Default store
**Fix**
Create a wrapper that implements the go-retryablehttp libraries log interface and wrap our own sdk logger in it so all http requests use the custom logger. 
Get the logger first before we setup the default cache/store to make sure we use the passed in logger for them if it's provided.
> (FFM-7327) Use custom logger for startup and http requests

- client/config.go
- storage/storage.go
**Issue**
We have 2 remaining logs that use fmt.Println/fmt.Printf instead of using the passed in logger.
These present as errors on startup when run inside our containers on ff-proxy and our own backend servers and cause confusion and clutter the logs. 
**Fix**
Log them as warnings using the actual sdk logger
> (FFM-7347) Remove mkdir error log on startup

- client/client.go
- stream/sse.go
- stream/stream.go
**What**
- Makes sure we call `onStreamError` anytime we break out of the SubscribeWithContext function
- If an eventListener has been passed to the Proxy we call its `Pub` method with an error. This lets the eventListener know that the stream its listening to has disconnected
**Why**
- Currently we only call `onStreamError` if SubscribeWithContext returns an error. However if the stream is intentionally closed by the server rather than [bubbling up the EOF error the SSE library we're using swallows i](https://github.com/r3labs/sse/blob/c6d5381ee3ca63828b321c16baa008fd6c0b4564/client.go#L216)t. This means we never call `onStreamError` which means the SDK thinks it's still connected to the stream and receiving SSE events which means it stops getting any changes because it isn't operating …
> FFM-8067 Call onStreamError anytime we exit Subscribe

- client/client.go
- client/config.go
- client/options.go
- dto/key.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- stream/sse.go
**What**
- Adds a SetFlags and SetSegment methods to the repository
**Why**
The Proxy passes its cache to the SDK and lets it manage populating and updating the cache with flags & segments. The current SetFlag and SetSegment methods work for storing individual key/value pairs of flags and segments. But we need to be able to store all of the flags/segments for a given environment at a single key.
**Testing**
I updated my local proxy to use this version of the sdk and did some manual testing and its populating the cache properly
> FFM-8618 Add SetFlags & SetSegments methods

- analyticsservice/analytics.go
**Changes**
Downgrade errors sending metrics to warn level. These aren't essential and theres likely very little an end user can do about some transient issue sending metrics.
> (FFM-8400) Metrics sending error log level

- pkg/repository/repository.go
- pkg/repository/repository_test.go
**What**
- Makes sure that we refresh the cache whenever we call SetFlags if we have outdated flags in the cache 
- Adds unit tests
> FFM-9314 Refresh cache if FeatureConfigs are outdated

- evaluation/evaluator.go
- evaluation/evaluator_test.go
- pkg/repository/repository.go
This change supports improved memory usage of the evaluator code. It introduces a new function on the query interface GetFlagMap().  This returns a map of flags.
This is more optimal as the GetFlag function can also use a underlying map, it removes the need to maintain both a list and a map of flags for the caller of the evaluator.
> [FFM-9476]: Optimize memory usage

- README.md
- analyticsservice/analytics.go
- client/client.go
- client/client_test.go
- client/config.go
- client/errors.go
- client/options.go
- docs/further_reading.md
- examples/getting_started.go
- go.mod
- test_helpers/test_helpers.go
- types/clock.go
- types/error.go
This PR does the following
1. Adds a `WaitForInitialized` option which uses a channel approach, improving upon the `IsInitialized` method. 
`IsInitialized` can still be used for backwards compatibility.  
- if an error occurs during initialization, it will be returned to the caller along with a non-nil `client`. If any variation functions are called in this state an error will be logged and the default variation returned. If `close` is attempted to be called, an error will be logged and returned. 
2. Changes how client authentication retries are handled. Instead of retrying on all errors, forever:
- `WithMaxAuthRetries` option is available. Defaults to unlimited retries (if the error is retryable).
- Only retry on 500 errors
- Uses backoff/jitter
1. New unit tests for synchronous and …
> FFM-8662 Add WaitForInitialized / Improve Authentication Retries 

- analyticsservice/analytics.go
- client/client.go
- examples/tls/example.go
Uses the existing `WithHttpClient` option to provide custom TLS support.
- Now uses overridden  http client for metrics and SSE 
- Adds TLS example
- Custom CAs using local proxy
- Authentication
- Requests to features endpoint
- Streaming
- Metrics
- No custom http client/custom CAs provided.
> FFM-7010 Use SDK HTTP Client for all requests

- analyticsservice/analytics.go
- evaluation/util.go
- evaluation/util_test.go
- sdk_codes/sdk_codes.go
[FFM-10027] - Fall back to 'identifier' if bucketBy attribute is not found
What
Update BucketBy logic to fall back to the target's identifier if given BucketBy attribute is not found.
Why
Keep the SDK consistent with the behaviour of the other server SDKs.
Testing
Testgrid + manual
[FFM-10027]: https://harness.atlassian.net/browse/FFM-10027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-10027] - Fall back to identifier if bucketBy attribute is not found

- .harness/ffgolangserversdk.yaml
- client/client.go
- client/transport.go
**What**
- Adds a connection close header to the http requests to prevent connections being re-used
**Why**
- We were seeing every other POST /metrics request fail with an EOF error but when we ran with the debugger this didn't happen. After some research it seems like this can happen due to the way the http client tries to re-use connections. Adding this header means we'll close the connection once the request has completed
**Testing**
- Tested this fix out locally
> FFM-11006 Add Connection close header

- evaluation/evaluator.go
- evaluation/evaluator_test.go
Supports new `AND` rules:
- `GroupServingRule` is the new rule type sent by the backend. They are:
-  Evaluated by `Priority` 
- `GroupServingRule.Clauses` are AND'ed
-  Additional `GroupServingRule` with lesser priority are OR'd (with their clauses AND'ed). 
- If there are no `GroupServingRule` to evaluate, then we fall back to the legacy `Rule` which is OR`d. 
- Unit tests
> FFM-11164 Evaluate `AND` rules

- evaluation/evaluator.go
In the new `AND/OR` logic, if a group didn't match then the SDK would return `false` instead of iterating to the next group and checking it.  This has been fixed by using `continue` instead of `return false`
Migrated TestGrid scenarios
Before fix:
After fix:
> FFM-11194 `AND/OR`: Continue to next group rule

- .harness/ffgolangserversdk.yaml
- .harness/pull_request_input_set.yaml
Builds and pushes a TestGrid Docker image for each commit pushed to an open Pull Request
So we can pull the image for easy testing of changes in a local ff-sever test environment. Building the image locally can involve toil due to image architecture constraints, and other issues around using unpublished versions of the SDK.
Image is tagged with commit SHA and pushed to GCR correctly.
> FFM-10311 Build TestGrid image on PR

- .harness/ffgolangserversdk.yaml
- analyticsservice/analytics.go
- analyticsservice/analytics_test.go
- analyticsservice/safe_maps_test.go
- analyticsservice/safe_seen_targets_map.go
- client/client.go
- client/config.go
- client/options.go
- evaluation/util.go
- Adds a configurable limit, defaulting to 500k targets, to `seenTargets`.  
- Adds a configurable clearing schedule, defaulting to 24 hours, to `seenTargets` 
- Change bucketBy missing attribute log from `warn` to `debug` 
To provide a sensible default upper bound for this map. 
- New unit tests for size and clearing behaviour
- Manual smoke test
> FFM-11660 Add configurable limit to the seen targets map

- Makefile
Pipeline is failing as unable to install `golint` due to modules being disabled in the makefile.
> Maint: fix pipeline

- .harness/ffgolangserversdk.yaml
- go.mod
- go.sum
Upgrade golang.org/x/net package to 0.33.0 to resolve vulnerability.
https://github.com/harness/ff-golang-server-sdk/security/dependabot/25
> fix: [FFM-12309]: fix net vulnerability
